# Generated by Django 5.0.6 on 2024-06-10 06:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("selfchatgpt", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chathistory",
            options={},
        ),
    ]
