# Generated by Django 5.0.6 on 2024-06-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("selfchatgpt", "0003_user_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField()),
            ],
        ),
    ]
